# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c32fdc71b7c6e28d02aa3143344e0f1f77337e6adbb05b14d930f477dbced832bb7212ab8d676bafae355f8bc146081f4e6b593cdb1c74535a8103fc4b3d04d6

test:
  secret_key_base: 67bbdc3bbfcb1cd1cc6e31fb10ea8e6d2572b9d6f8affab94e674505bb41f3489d639ce853af25dde0287b2d31305929cc771ab2c1fd2ffb51eb7e48ca008060

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
